namespace GraphPlatform.Api.Models;

/// <summary>
/// A stored file: its metadata plus the object key of its content in the configured storage provider.
/// </summary>
/// <remarks>
/// <para>
/// Owner-agnostic on purpose. A file belongs to an organization, never directly to a Knowledge Base
/// or any other resource: each owning resource links to its files through its own table (today only
/// <see cref="KnowledgeBaseFile"/>), so a new owner adds a link table instead of a column here.
/// </para>
/// <para>
/// The name collides with <c>System.IO.File</c>, which implicit usings import everywhere. Code that
/// needs this type declares <c>using File = GraphPlatform.Api.Models.File;</c>. That alias is
/// per file, never global, because the storage providers use <c>System.IO.File</c>.
/// </para>
/// <para>
/// The API owns this table's DDL. The Python <c>common</c> project maps it on <c>ApiOwnedBase</c>
/// (<c>common.models.file</c>), so column names stay the EF defaults (PascalCase) and must not be
/// renamed on one side only.
/// </para>
/// </remarks>
public class File
{
    /// <summary>Maximum length of the generated resource id.</summary>
    public const int IdMaxLength = 255;

    /// <summary>Maximum length of the original file name.</summary>
    public const int FileNameMaxLength = 255;

    /// <summary>Maximum length of the content type.</summary>
    public const int ContentTypeMaxLength = 255;

    /// <summary>Maximum length of a storage key, matching the storage contract (ADR-0006).</summary>
    public const int StorageKeyMaxLength = 1024;

    /// <summary>Stable resource id, generated by the API.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Organization that owns the file (ADR-0002, Decision 1).</summary>
    public string OrganizationId { get; set; } = string.Empty;

    /// <summary>Original file name supplied by the uploader, without any directory part.</summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>MIME content type recorded at upload.</summary>
    public string ContentType { get; set; } = string.Empty;

    /// <summary>Size of the stored content in bytes.</summary>
    public long Size { get; set; }

    /// <summary>
    /// Storage object key, the canonical reference to the content (never a path or URL).
    /// </summary>
    public string StorageKey { get; set; } = string.Empty;

    /// <summary>Processing status.</summary>
    public FileStatus Status { get; set; } = FileStatus.Uploaded;

    /// <summary>When the file was uploaded (UTC).</summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>When the row was last changed (UTC).</summary>
    public DateTimeOffset UpdatedAtUtc { get; set; }

    /// <summary>
    /// Builds the storage key for a file. Neither the owner nor the uploader's file name is part of
    /// it, so the key never depends on caller-assigned ids or names.
    /// </summary>
    public static string BuildStorageKey(string organizationId, string fileId) =>
        $"organizations/{organizationId}/files/{fileId}/content";
}

/// <summary>Processing states for a stored file.</summary>
public enum FileStatus
{
    /// <summary>Stored and awaiting processing.</summary>
    Uploaded,

    /// <summary>Being processed (for Knowledge Base files, by the ingestion worker).</summary>
    Processing,

    /// <summary>Processed successfully.</summary>
    Processed,

    /// <summary>Processing failed.</summary>
    Failed,
}
