namespace GraphPlatform.Api.Models;

/// <summary>
/// One source file within an <see cref="IndexJob"/>. Mirrors
/// <c>ingestion_worker/src/ingestion_worker/models/index_file.py</c>'s <c>IndexFile</c> exactly,
/// including its snake_case column names.
/// </summary>
/// <remarks>
/// Phase 1 of ADR-0005 treats a whole Knowledge Base as one file conceptually for graph/embedding
/// writes, but the API still creates one row per uploaded <see cref="File"/> so the job's
/// <see cref="IndexJob.TotalFiles"/> is fixed before any fan-out — the per-file fan-out itself is
/// Phase 2.
/// </remarks>
public class IndexFile
{
    /// <summary>Maximum length of <see cref="Id"/> and every other id/string column here.</summary>
    public const int IdMaxLength = 255;

    /// <summary>Stable resource id, generated by the API at publish time.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Owning job.</summary>
    public string IndexJobId { get; set; } = string.Empty;

    /// <summary>Navigation to the owning job.</summary>
    public IndexJob IndexJob { get; set; } = null!;

    /// <summary>The uploaded <see cref="File"/> this row tracks.</summary>
    public string FileId { get; set; } = string.Empty;

    /// <summary>Current processing status.</summary>
    public IndexFileStatus Status { get; set; } = IndexFileStatus.Pending;

    /// <summary>Number of processing attempts made so far.</summary>
    public int Attempts { get; set; }

    /// <summary>Error message from the most recent failed attempt, if any.</summary>
    public string? Error { get; set; }

    /// <summary>When the worker started processing this file (UTC), or null before that.</summary>
    public DateTimeOffset? StartedAt { get; set; }

    /// <summary>When this file reached a terminal status (UTC), or null while still in progress.</summary>
    public DateTimeOffset? CompletedAt { get; set; }
}

/// <summary>Processing states for an <see cref="IndexFile"/> (ADR-0005).</summary>
public enum IndexFileStatus
{
    /// <summary>Created, not yet picked up for extraction.</summary>
    Pending,

    /// <summary>Extraction in progress.</summary>
    Extracting,

    /// <summary>Extraction completed successfully.</summary>
    Extracted,

    /// <summary>Extraction failed.</summary>
    Failed,

    /// <summary>Deliberately not processed.</summary>
    Skipped,
}
