namespace GraphPlatform.Api.Models;

/// <summary>
/// One ingestion request for a Knowledge Base, tracked through the worker's dispatch/fan-in
/// lifecycle (ADR-0005).
/// </summary>
/// <remarks>
/// <para>
/// This is the management-facing side of a row the API creates and the Python ingestion worker
/// claims and advances. Columns mirror
/// <c>ingestion_worker/src/ingestion_worker/models/index_job.py</c>'s <c>IndexJob</c> exactly,
/// including its snake_case column names — see <c>AppDbContext</c>'s explicit
/// <c>HasColumnName</c> mapping, the first table in this API to need one, since every other
/// EF-owned table keeps PascalCase columns.
/// </para>
/// <para>
/// The API only ever writes <see cref="Status"/>=<see cref="IndexJobStatus.Queued"/> at creation
/// time (<c>KnowledgeBasesController.PublishKnowledgeBase</c>); every other transition belongs to
/// the worker's <c>IndexJobStore</c>. The read endpoint
/// (<c>GET .../knowledge-bases/{kbId}/index-jobs/{jobId}</c>) is this API's only other touch point.
/// </para>
/// </remarks>
public class IndexJob
{
    /// <summary>Maximum length of <see cref="Id"/> and every other id/string column here.</summary>
    public const int IdMaxLength = 255;

    /// <summary>Stable resource id, generated by the API at publish time.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Organization that owns the underlying Knowledge Base (ADR-0002, Decision 1).</summary>
    public string OrganizationId { get; set; } = string.Empty;

    /// <summary>Knowledge Base this job ingests.</summary>
    public string KnowledgeBaseId { get; set; } = string.Empty;

    /// <summary>Navigation to the Knowledge Base this job ingests.</summary>
    public KnowledgeBase KnowledgeBase { get; set; } = null!;

    /// <summary>
    /// The Apache Age graph this job writes to, computed once at publish time by
    /// <c>GraphNames.ForOrganization</c>.
    /// </summary>
    public string GraphName { get; set; } = string.Empty;

    /// <summary>Current lifecycle status.</summary>
    public IndexJobStatus Status { get; set; } = IndexJobStatus.Queued;

    /// <summary>Total number of files the job was created with; fixed at publish time.</summary>
    public int TotalFiles { get; set; }

    /// <summary>Number of files the worker has finished processing (success or failure).</summary>
    public int ProcessedFiles { get; set; }

    /// <summary>Number of files the worker has marked failed.</summary>
    public int FailedFiles { get; set; }

    /// <summary>
    /// Whether graph construction has been dispatched. Guards the fan-in so it fires exactly once.
    /// </summary>
    public bool GraphDispatched { get; set; }

    /// <summary>
    /// The organization's active embedding model at publish time (ADR-0002, Decision 3), or null
    /// when none was configured.
    /// </summary>
    public string? EmbeddingModelId { get; set; }

    /// <summary>Identity user id of the caller who published the Knowledge Base.</summary>
    public string? RequestedBy { get; set; }

    /// <summary>Terminal error message, set when <see cref="Status"/> is a failure state.</summary>
    public string? Error { get; set; }

    /// <summary>When the job row was created (UTC).</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>When the worker claimed the job (UTC), or null while still queued.</summary>
    public DateTimeOffset? StartedAt { get; set; }

    /// <summary>When the job reached a terminal status (UTC), or null while still in progress.</summary>
    public DateTimeOffset? CompletedAt { get; set; }

    /// <summary>Files tracked under this job.</summary>
    public ICollection<IndexFile> Files { get; set; } = [];
}

/// <summary>Lifecycle states for an <see cref="IndexJob"/> (ADR-0005).</summary>
public enum IndexJobStatus
{
    /// <summary>Created by the API, not yet claimed by the worker's dispatcher.</summary>
    Queued,

    /// <summary>Claimed by the worker and in progress.</summary>
    Running,

    /// <summary>Every file processed successfully.</summary>
    Completed,

    /// <summary>Some files processed successfully, at least one failed.</summary>
    PartiallyFailed,

    /// <summary>The job failed outright.</summary>
    Failed,

    /// <summary>The job was cancelled before completion.</summary>
    Cancelled,
}
