namespace GraphPlatform.Api.Models;

/// <summary>
/// A file uploaded to a knowledge base. The bytes live in the configured storage provider under
/// <see cref="StorageKey"/>; this row holds the metadata and that reference.
/// </summary>
/// <remarks>
/// The API owns this table's DDL, like <c>knowledge_base</c>. The Python <c>common</c> project maps
/// it on <c>ApiOwnedBase</c> (<c>common.models.knowledge_base_file</c>), so column names stay the EF
/// defaults (PascalCase) and must not be renamed on one side only.
/// </remarks>
public class KnowledgeBaseFile
{
    /// <summary>Maximum length of the generated resource id.</summary>
    public const int IdMaxLength = 255;

    /// <summary>Maximum length of the original file name.</summary>
    public const int FileNameMaxLength = 255;

    /// <summary>Maximum length of the content type.</summary>
    public const int ContentTypeMaxLength = 255;

    /// <summary>Maximum length of a storage key, matching the storage contract (ADR-0006).</summary>
    public const int StorageKeyMaxLength = 1024;

    /// <summary>Stable resource id, generated by the API.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Knowledge base this file belongs to.</summary>
    public string KnowledgeBaseId { get; set; } = string.Empty;

    /// <summary>Navigation to the owning knowledge base.</summary>
    public KnowledgeBase KnowledgeBase { get; set; } = null!;

    /// <summary>
    /// Owning organization, denormalized from the knowledge base so side-table reads can be scoped
    /// without a join (ADR-0002, Decision 1).
    /// </summary>
    public string OrganizationId { get; set; } = string.Empty;

    /// <summary>Original file name supplied by the uploader, without any directory part.</summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>MIME content type recorded at upload.</summary>
    public string ContentType { get; set; } = string.Empty;

    /// <summary>Size of the stored content in bytes.</summary>
    public long Size { get; set; }

    /// <summary>
    /// Storage object key, the canonical reference to the content (never a path or URL).
    /// </summary>
    public string StorageKey { get; set; } = string.Empty;

    /// <summary>Processing status.</summary>
    public KnowledgeBaseFileStatus Status { get; set; } = KnowledgeBaseFileStatus.Uploaded;

    /// <summary>When the file was uploaded (UTC).</summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>When the row was last changed (UTC).</summary>
    public DateTimeOffset UpdatedAtUtc { get; set; }

    /// <summary>Builds the storage key for a file. The uploader's file name is never part of it.</summary>
    public static string BuildStorageKey(string organizationId, string knowledgeBaseId, string fileId) =>
        $"organizations/{organizationId}/knowledge-bases/{knowledgeBaseId}/files/{fileId}/content";
}

/// <summary>Processing states for a knowledge base file.</summary>
public enum KnowledgeBaseFileStatus
{
    /// <summary>Stored and awaiting ingestion.</summary>
    Uploaded,

    /// <summary>Being processed by the ingestion worker.</summary>
    Processing,

    /// <summary>Processed successfully.</summary>
    Processed,

    /// <summary>Processing failed.</summary>
    Failed,
}
