embedding_dimensions: 768

models:
  # - display_name: "Groq OpenAI OSS 20B"
  #   provider: groq
  #   name: openai/gpt-oss-20b
  #   auth_mode: api_key
  #   type: [thinking]
  #   api_key_env: GROQ_API_KEY
  - display_name: "Openrouter"
    provider: openrouter
    name: google/gemma-4-26b-a4b-it:free
    auth_mode: api_key
    type: [thinking]
    api_key_env: OPENROUTER_API_KEY
  # - display_name: "Gemini"
  #   provider: gemini
  #   name: gemma-4-26b-a4b-it
  #   auth_mode: api_key
  #   type: [thinking]
  #   api_key_env: GEMINI_API_KEY
  - display_name: "Gemini Embedding 2"
    provider: gemini
    name: gemini-embedding-2
    auth_mode: api_key
    type: [embedding]
    api_key_env: GEMINI_API_KEY
    embedding_dimension: 768
